name: kbm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  device_info_plus: ^3.2.3
  connectivity: ^3.0.3
  dartz: ^0.10.1
  flutter_screenutil: ^5.4.0+1
  device_preview: ^1.0.0
  sentry_flutter: ^6.4.0
  google_fonts: ^2.3.1
  carousel_slider: ^4.1.1
  dio: ^4.0.6
  get_it: ^7.2.0
  provider: ^6.0.3
  cached_network_image: ^3.0.0
  flutter_barcode_scanner: ^2.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg